spring:
  jackson:
    time-zone: America/Sao_Paulo

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: votacao
    password: votacao
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    schemas: VOTACAO
    clean-disabled: false

  redis:
    url: redis://redis:6379
    cache:
      type: redis

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG

scheduler:
  sessao:
    delay: 60000 # 1 minuto
