spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: votacao
    password: votacao
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    schemas: VOTACAO
    clean-disabled: false

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG
